"                               ___           ___           ___
"      ___        ___          /__/\         /  /\         /  /\
"     /__/\      /  /\        |  |::\       /  /::\       /  /:/
"     \  \:\    /  /:/        |  |:|:\     /  /:/\:\     /  /:/ 
"      \  \:\  /__/::\      __|__|:|\:\   /  /:/~/:/    /  /:/  ___
"  ___  \__\:\ \__\/\:\__  /__/::::| \:\ /__/:/ /:/___ /__/:/  /  /\
" /__/\ |  |:|    \  \:\/\ \  \:\~~\__\/ \  \:\/:::::/ \  \:\ /  /:/
" \  \:\|  |:|     \__\::/  \  \:\        \  \::/~~~~   \  \:\  /:/
"  \  \:\__|:|     /__/:/    \  \:\        \  \:\        \  \:\/:/
"   \__\::::/      \__\/      \  \:\        \  \:\        \  \::/
"       ~~~~                   \__\/         \__\/         \__\/



" prepend 'no' to switch an option off
" e.g.: set ruler != set noruler


" default
unlet! skip_defaults_vim		" start default vim settings
source $VIMRUNTIME/defaults.vim
set nocompatible				" set compatibility to Vim only.
filetype plugin indent on   
filetype plugin on				" enable filetype plugins



"" general options

" UI
set ruler				" always show current position
syntax on				" turn on syntax highlighting.
set number				" show line numbers
if has('mouse')
	set mouse=a			" enable using the mouse if available
endif
set scrolloff=3			" keep a few lines of contect arround the cursor
set noshowmode			" don’t show currenet mode
set laststatus=2		" always display the statusline in all windows
set showtabline=2		" always display the tabline, even if there is only one tab
set t_Co=256			" set tabline color to white
set display=truncate	" show @@@ in the last line if it’s truncated


" misc
set history=1000					" remember a ton of commands
set clipboard=unnamed				" use OS clipboard as default yank buffer
set spell							" enable spell-check
set spelllang=en,es,it					" enable spell-check in english, spanish, and italian
set backspace=indent,eol,start		" backspace over everything
set encoding=utf-8					" default encoding
set wildmenu						" display completion matches in a status line
set nrformats-=octal				" don’t recognize numbers starting with zero as octal
set path+=**						" recursively look through subdirectories when dealing with filepaths


" whitespace and indentation
set tabstop=4					" a tab is four spaces
set listchars=tab:>-,trail:-	" display tabs with pretty colors
set shiftwidth=4				" N spaces while auto-indenting
set softtabstop=4				" N spaces while editing (deletes groups of N spaces)
set smartindent					" seems to do a decent job with indenting


" searching
set ignorecase		" ignore case when searching
set incsearch		" show partial matches for a search
set hlsearch		" highlight all matching phrases



"" mappings

" remove arrow keys and hjkl
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
noremap <Up> <Nop>
noremap j <Nop>
noremap h <Nop>
noremap l <Nop>
noremap k <Nop>

set whichwrap=b,s,<,>,[,]		" allow <Left>, <Right>, <Backspace>, and <Space>, to move the cursor from the start of a line to the begining of the other and viceversa


"" no se que categoria meter
packadd! matchit		" enable matchit plugin
