#!/bin/bash

# enumerates every file inside the given directory.
# change "i" to start from 0 or 1 or whatever number you like.

a=1
cd ~/.wallpaper/nice
for i in *; do
  new=$(printf "%04d.jpg" "$a") #04 pad to length of 4
  mv -i -- "$i" "$new"
  let a=a+1
done
