#!/bin/bash

usage()
{
    echo -e "Usage: $(basename "$0") COLOR"
    exit 1
}

color_value()
{
    local search
    case $1 in
        FOREGROUND) search="foreground:"    ;;
        BACKGROUND) search="background:"    ;;
        CURSOR)     search="cursorColor:"   ;;
        BLACK)      search="color0:"        ;;
        RED)        search="color1:"        ;;
        GREEN)      search="color2:"        ;;
        YELLOW)     search="color3:"        ;;
        BLUE)       search="color4:"        ;;
        MAGENTA)    search="color5:"        ;;
        CYAN)       search="color6:"        ;;
        WHITE)      search="color7:"        ;;
        ALTBLACK)   search="color8:"        ;;
        ALTRED)     search="color9:"        ;;
        ALTGREEN)   search="color10:"       ;;
        ALTYELLOW)  search="color11:"       ;;
        ALTBLUE)    search="color12:"       ;;
        ALTMAGENTA) search="color13:"       ;;
        ALTCYAN)    search="color14:"       ;;
        ALTWHITE)   search="color15:"       ;;
        *)          usage                   ;;
    esac
    [[ -n $search ]] && xrdb -query | grep $search | awk '{print $NF}'
}

[[ $# -ne 1 ]] && usage

color_value "${1^^}"
