#!/bin/bash

readonly dependencies=("maim" "xclip" "feh")
for dependency in "${dependencies[@]}"; do
  if ! command -v "$dependency" &> /dev/null; then
    echo "Missing dependency: $dependency"
    exit 65
  fi
done

readonly path="$HOME"/.screenshots
[ -d "$path" ] || mkdir -pv "$path"

date=$(date "+%Y-%m-%d")
readonly date
number=$(find "$path" -name "${date}*" | wc -l)
readonly number
name="${path}"/"${date}"-"${number}".png
readonly name

if [ "$1" = "cut" ]; then
  cut="s"
else
  cut=""
fi

maim -uo"$cut" | tee "$name" | xclip -selection clipboard -t image/png
feh "$name"
