#!/bin/sh

# Create a pastebin link to commands or file content
# Add ?<lang> at the end to get syntax highlighting

# Usage:
# $ sprunge file
# $ sprunge some command
# $ some command | sprunge

# Example:
# $ sprunge ~/.bashrc --> http://sprunge.us/abcdef
#  with highlighting --> http://sprunge.us/abcdef?bash

# The explanation of the following code is left as an exercise to the user

__sprunge() {
  if [ -z "$1" ] || [ -r "$1" ]; then
    curl -F "sprunge=<${1:--}" sprunge.us
  else
    printf '$%s\n\n%s' "$*" "$("$@")" 2>&1 | __sprunge
  fi
}

__sprunge "$@"
