#!/bin/sh

# play music from youtube

# usage: yt-play GENRE

# example:
#   $ yt-play lofi

# supported genres:
#   jazz
#   lofi
#   synthwave

usage() {
  echo "Usage: $(basename "$0") (lofi | synthwave | jazz)" >&2
}

play() {
  mpv --no-video "$1" > /dev/null 2>&1
}

[ "$#" -lt 1 ] && usage && exit 22

command -v "mpv" "youtube-dl" > /dev/null 2>&1 \
  || { echo "Error - missing dependency" && exit 65; }

case "$1" in
  "lofi") play "https://www.youtube.com/watch?v=5qap5aO4i9A" ;;
  "synthwave") play "https://www.youtube.com/watch?v=BbGOa8UIbAc" ;;
  "jazz") play "https://www.youtube.com/watch?v=VR4H81bz-Bs" ;;
  *) usage && exit 22 ;;
esac
