#!/bin/sh

# play music from youtube

usage() {
  echo "usage: $(basename "$0") GENRE"
  echo "supported genres:"
  echo "  jazz"
  echo "  lofi"
  echo "  synthwave"
  exit "$1"
}

play() {
  mpv --no-video "$1" > /dev/null 2>&1
}

[ "$#" -lt 1 ] && usage 22

command -v "mpv" "youtube-dl" > /dev/null 2>&1 \
  || { echo "Error - missing dependency" && exit 65; }

case "$1" in
  "lofi") play "https://www.youtube.com/watch?v=5qap5aO4i9A" ;;
  "synthwave") play "https://www.youtube.com/watch?v=BbGOa8UIbAc" ;;
  "jazz") play "https://www.youtube.com/watch?v=VR4H81bz-Bs" ;;
  *) usage 22 ;;
esac
