#!/bin/sh
bspc rule -r "*"

## Variables
config="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/config"

## Monitor Settings
[ -x "$config"/monitors_setup.sh ] && "$config"/monitors_setup.sh

## Desktop Settings
[ -x "$config"/desktop_setup.sh ] && "$config"/desktop_setup.sh

## Global Settings
bspc config automatic_scheme    alternate

bspc config borderless_monocle	true
bspc config gapless_monocle 	true
bspc config single_monocle 	true

bspc config pointer_modifier	    	control
bspc config click_to_focus	        	none

## Node Settings
bspc config border_width	2

## Rule Commands

# General
bspc rule -a feh state=floating

# Desktop 9
bspc rule -a discord desktop=^9 follow=on state=tiled
bspc rule -a TelegramDesktop desktop=^8 follow=on state=tiled

# Desktop 10
bspc rule -a "$TERMINAL":"$TERMINAL":pulsemixer \
  desktop=^10 follow=off state=floating rectangle=500x660+1401+366

bspc rule -a "$TERMINAL":"$TERMINAL":ncspot \
  desktop=^10 follow=off state=floating rectangle=1378x924+15+15

bspc config external_rules_command "$config"/external_rules.sh

## Autostart
[ -x "$config"/autostart.sh ] && "$config"/autostart.sh
