#!/bin/bash
bspc rule -r "*"

# Enviroment
export PATH="${PATH}:$HOME/.bin"

# Variables
win_gaps=4
padding=15
panel_size=35

## Autostart
[[ -x $HOME/.config/bspwm/config/autostart.sh ]] && . "$HOME"/.config/bspwm/config/autostart.sh

## Monitor Settings
[[ -x $HOME/.config/bspwm/config/monitors_setup.sh ]] && . "$HOME"/.config/bspwm/config/monitors_setup.sh

bspc config  top_padding       $((padding - win_gaps))
bspc config  bottom_padding    $((padding - win_gaps + panel_size))
bspc config  left_padding      $((padding - win_gaps))
bspc config  right_padding     $((padding - win_gaps))

## Global Settings
bspc config automatic_scheme	alternate
bspc config initial_polarity	second_child

bspc config split_ratio	    	0.5
bspc config borderless_monocle	true
bspc config gapless_monocle 	true
bspc config single_monocle  	false

bspc config pointer_modifier	    	control
bspc config pointer_action1	        	move
bspc config pointer_action2	        	resize_side
bspc config pointer_action3	        	resize_corner
bspc config click_to_focus	        	none
bspc config focus_follows_pointer	    true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

## Desktop Settings
bspc config window_gap		$win_gaps

## Node Settings
bspc config border_width	2

## Rule Commands

# General
bspc rule -a feh state=floating

# Desktop 9
bspc rule -a discord desktop=^9 follow=on state=tiled

# Desktop 10
bspc rule -a Pavucontrol desktop=^10 follow=off state=floating

## Colors
[[ -x $HOME/.config/bspwm/config/color_setup.sh ]] && . "$HOME"/.config/bspwm/config/color_setup.sh
