#!/bin/sh

bspc rule -r "*"

## Variables
config="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/config"

## Monitor Settings
[ -x "$config"/monitors_setup.sh ] && "$config"/monitors_setup.sh

## Desktop Settings
[ -x "$config"/desktop_setup.sh ] && "$config"/desktop_setup.sh

## Global Settings
bspc config automatic_scheme alternate

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config pointer_modifier control
bspc config click_to_focus none

## Node Settings
bspc config border_width 2

## Rule Commands
# General
[ -x "$config"/external_rules.sh ] \
  && bspc config external_rules_command "$config"/external_rules.sh
bspc rule -a feh state=floating
bspc rule -a Pomello state=floating sticky=on

# Desktop 1
bspc rule -a "$BROWSER" desktop=^1

# Desktop 2
bspc rule -a "$TERMINAL" desktop=^2

# Desktop 3
bspc rule -a jetbrains-idea desktop=^3
bspc rule -a chromium desktop=^3

# Desktop 4
bspc rule -a steam desktop=^4
bspc rule -a "*:*:Steam" desktop=^4

# Desktop 7
bspc rule -a "Microsoft Teams - Preview" desktop=^7

bspc rule -a "$TERMINAL":"$TERMINAL":neomutt desktop=^7

# Desktop 8
bspc rule -a TelegramDesktop desktop=^8 follow=on

# Desktop 9
bspc rule -a discord desktop=^9

# Desktop 10
bspc rule -a "$TERMINAL":"$TERMINAL":pulsemixer \
  desktop=^10 state=floating rectangle=500x660+1401+366

bspc rule -a "$TERMINAL":"$TERMINAL":ncspot \
  desktop=^10 state=floating rectangle=1378x924+15+15

## Autostart
[ -x "$config"/autostart.sh ] && "$config"/autostart.sh
