# Options
album_column            = false
flip_status_indicators  = true
hide_display_names      = true
library_tabs            = [ "tracks", "playlists", "podcasts" ]
repeat                  = "playlist"
volnorm                 = true

[keybindings]
"G" = "move bottom"
"d" = "noop"
"g" = "move top"
"p" = "playpause"
