#!/bin/sh

# dec-brightness
# the same as inc-brightness, just the exact opposite

usage() {
  echo "Usage: $0 <increment>" && exit "$1"
}

[ "$#" -ne 1 ] && usage 7

monitor=$(xrandr --query | grep "primary" | cut -f1 -d" ")

actual_brightness=$(xrandr --verbose | awk '/Brightness/ { print $2; exit }')

# $1 holds how much the brightness is going to decrease
min_brightness=0.1
wanted_brightness=$(echo "$actual_brightness-$1" | bc)

[ "$(echo "$wanted_brightness > $min_brightness" | bc -l)" -eq 1 ] \
  && new_brightness="$wanted_brightness" \
  || new_brightness="$min_brightness"

xrandr --output "$monitor" --brightness "$new_brightness"
