#!/bin/bash

# inc-brightness
# uses "brightness" command but treats it's arguments as increments
# instead of imperative values.
# also keeps brightness between 0.1 and 1 because what's the point of not doing it

#primary_monitor=$(xrandr -q | grep primary | cut -f1 -d" ")
actual_brightness=$(xrandr --verbose | awk '/Brightness/ { print $2; exit }')

# $1 holds how much the brightness is going to increase
max_brightness=1
wanted_brightness=$(bc <<< "$actual_brightness+$1")

[[ $(echo "$wanted_brightness < $max_brightness" | bc -l) ]] && new_brightness=$wanted_brightness || new_brightness=$max_brightness

xrandr --output eDP-1 --brightness $new_brightness
